## Tensor

텐서란 리스나 행렬과 비슷한 구조를 가지고 있는 데이터 타입 형태로 pytorch에서 다루는 데이터 셋은 텐서로 이루어져 있다.   

pytorch에서 제공하는 메소드들을 이용해서 list나 array를 텐서로 쉽게 바꿀수 있다. 


### 1. Initialization 

In [1]:
import torch 
import numpy as np 

In [4]:
# list to tensor 

data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [8]:
# array to tensor

np_array = np.array(data)
y_data = torch.from_numpy(np_array)
y_data

tensor([[1, 2],
        [3, 4]])

In [9]:

x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씁니다.
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9739, 0.1200],
        [0.7343, 0.1710]]) 



In [10]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9459, 0.1782, 0.5409],
        [0.6856, 0.2196, 0.9080]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 2. Attribute

In [14]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")


Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### 3. Operation 

pytorch에서 여러 텐서 연산 메소드를 제공한다.  
각 연산들은 cpu보다 gpu에서 일반적으로 연산이 빠르게 실행된다. 

In [18]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
tensor.device

device(type='cuda', index=0)

In [30]:
data = np.array(range(1,28,1))
data = torch.from_numpy(data.reshape(3,3,3))
data

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])

In [34]:

tensor = data
print('First row: ',tensor[0])

print("===================================")

print('First column: ', tensor[:, 0])
print('First column: ', tensor[:, 0,:])

print("===================================")

print('Last column:', tensor[..., -1])
print(tensor[:,:,-1])


tensor[:,1] = 0
print(tensor)

First row:  tensor([[1, 2, 3],
        [0, 0, 0],
        [7, 8, 9]])
First column:  tensor([[ 1,  2,  3],
        [10, 11, 12],
        [19, 20, 21]])
First column:  tensor([[ 1,  2,  3],
        [10, 11, 12],
        [19, 20, 21]])
Last column: tensor([[ 3,  0,  9],
        [12,  0, 18],
        [21,  0, 27]])
tensor([[ 3,  0,  9],
        [12,  0, 18],
        [21,  0, 27]])
tensor([[[ 1,  2,  3],
         [ 0,  0,  0],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [ 0,  0,  0],
         [16, 17, 18]],

        [[19, 20, 21],
         [ 0,  0,  0],
         [25, 26, 27]]])


In [37]:
tensor = torch.ones(3,3)

In [38]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [39]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [42]:
agg = tensor.sum()
print(agg)
agg_item = agg.item() # agg에 값이 단 하나일 경우 .item() 메소드를 이용하여 값을 반환 할 수 있다. 
print(agg_item, type(agg_item))

tensor(9.)
9.0 <class 'float'>


In [43]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

# #바꿔치기 연산은 메모리를 일부 절약하지만, 기록(history)이 즉시 삭제되어
# 도함수(derivative) 계산에 문제가 발생할 수 있다. 
# 따라서, 사용을 권장하지 않는다.

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])


## 4. bridge

cpu상의 텐서와 numpy배열은 메모리 공간을 공유하기 떄문에 하나를 변경하면 다른 하나도 변경된다.

In [50]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")


t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [51]:
t = torch.ones(5)
t=t.to('cuda')
print(t.device)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")


t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

cuda:0
t: tensor([1., 1., 1., 1., 1.], device='cuda:0')


TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

위 처럼 cpu상에서 텐서를 array로 변환했을 경우에는 두 데이터가 메모리 공간을 공유하지만   
gpu상에서의 텐서는 메모리 공간을 공유할 뿐만 아니라 애초에 tensor를 numpy로 변환하는 것 자체가 불가하다. 

In [54]:
n = np.ones(5)
t = torch.from_numpy(n)
print(t.device)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

cpu
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
